import React from 'react'

export default function Content() {
  return (
    <div className='d-flex flex-column col-9'>
        <h1 className='border-bottom border-3 pb-2'>Terms Of Use</h1>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
        <small className='mt-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus posuere nisi, ac ornare nunc. Aliquam erat volutpat. Duis dignissim volutpat consequat. Mauris sed condimentum leo. Etiam sed nibh mi. Curabitur odio turpis, egestas eget imperdiet ac, vehicula id augue. Mauris vitae maximus ipsum. In hac habitasse platea dictumst. Duis vitae condimentum mauris.</small>
    </div>
  )
}
